(ns litpool (:require [clojure.string :as str] ["fs" :as fs]))
(def args (vec *command-line-args*))
(def parts (->> (str/split-lines (fs/readFileSync (first args) "utf8"))
                (remove str/blank?) vec))
(defn arms [codes]
  (let [n (count codes)]
    (str (str/join "" (for [i (range (dec n))] (str "(if (= i " i ") " (nth codes i) " ")))
         (nth codes (dec n)) (str/join "" (repeat (dec n) ")")))))
(let [codes (vec (mapcat #(map (fn [c] (.charCodeAt c 0)) (seq %)) parts))
      offs (loop [ps parts at 0 acc []]
             (if (empty? ps) acc
                 (recur (rest ps) (+ at (count (first ps)))
                        (conj acc [(first ps) at (count (first ps))]))))
      out (str ";; GENERATED by scripts/gen-device-literal-pool.cljs from "
               (first args) " -- do not hand-edit.\n"
               (str/join "" (for [[s at n] offs]
                              (str ";;   (put-lit out at " at " " n ")  " (pr-str s) "\n")))
               ";; pool length " (count codes) "\n"
               "(defn lit [i] " (arms codes) ")\n")]
  (fs/writeFileSync (second args) out)
  (println "WROTE" (second args) "chars" (count codes) "parts" (count parts)))
