(ns aiueos.provider.cloud-own-test
  "The same loopback proofs as `cloud-tls-test`, run through this workspace's
  own TLS 1.3 and HTTP/1.1 instead of `java.net.http`.

  Every test here that has a platform counterpart runs **both** transports over
  the same server, because the claim is not that the own path works -- it is
  that the two paths answer the same question the same way. A behaviour proved
  on one and assumed on the other is the shape ADR-0077 exists to avoid."
  (:require [aiueos.cloud-live :as live]
            [aiueos.provider.cloud :as provider]
            [aiueos.provider.cloud-own :as own]
            [clojure.java.io :as io]
            [clojure.string :as str]
            [clojure.test :refer [deftest is testing]]
            [grant.cloud :as cloud]
            [tls.cert :as cert]
            [tls.provider.jvm :as jvm])
  (:import [com.sun.net.httpserver HttpExchange HttpHandler HttpsConfigurator HttpsServer]
           [java.net InetSocketAddress ServerSocket]
           [java.security KeyStore]
           [java.security.cert X509Certificate]
           [javax.net.ssl KeyManagerFactory SSLContext]))

(def hello "hello world")
(def hello-digest "b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9")
(def raw-cid "bafkreifzjut3te2nhyekklss27nh3k72ysco7y32koao5eei66wof36n5e")
(def cid-path (str "/ipfs/" raw-cid))
(def store-pass "changeit")

;; ── one server, reachable by both transports ──────────────────────────────

(def ^:private keystore
  "One self-signed certificate for 127.0.0.1, generated by the JDK's own
  keytool. Generated rather than checked in, because a private key in the
  repository is a private key in the repository."
  (delay
    (let [dir (doto (io/file (System/getProperty "java.io.tmpdir")
                             (str "aiueos-own-" (System/currentTimeMillis)))
                (.mkdirs))
          path (str (io/file dir "server.p12"))
          pb (ProcessBuilder.
              ^"[Ljava.lang.String;"
              (into-array String [(str (System/getProperty "java.home") "/bin/keytool")
                                  "-genkeypair" "-alias" "aiueos"
                                  "-keyalg" "RSA" "-keysize" "2048"
                                  "-sigalg" "SHA256withRSA"
                                  "-dname" "CN=localhost" "-validity" "1"
                                  "-keystore" path "-storetype" "PKCS12"
                                  "-storepass" store-pass "-keypass" store-pass
                                  "-ext" "SAN=IP:127.0.0.1"]))
          proc (.start (.redirectErrorStream pb true))
          out (slurp (.getInputStream proc))]
      ;; A missing keytool must fail the test, not skip it: a suite that
      ;; silently does not run reports the same green as one that ran.
      (assert (zero? (.waitFor proc)) (str "keytool failed: " out))
      (let [ks (KeyStore/getInstance "PKCS12")]
        (with-open [in (io/input-stream path)]
          (.load ks in (.toCharArray store-pass)))
        ks))))

(defn- server-pin []
  (provider/spki-sha256-hex ^X509Certificate (.getCertificate ^KeyStore @keystore "aiueos")))

(defn- server-ssl-context ^SSLContext []
  (let [kmf (KeyManagerFactory/getInstance (KeyManagerFactory/getDefaultAlgorithm))]
    (.init kmf ^KeyStore @keystore (.toCharArray store-pass))
    (doto (SSLContext/getInstance "TLS")
      (.init (.getKeyManagers kmf) nil nil))))

(defn- with-https-server
  "Run BODY against a live https server. `:hits` collects the paths that were
  requested and `:headers` the request headers of each, so a test can assert
  what did NOT reach the wire as well as what did."
  [handler body]
  (let [server (HttpsServer/create (InetSocketAddress. "127.0.0.1" 0) 0)
        hits (atom [])
        headers (atom [])]
    (.setHttpsConfigurator server (HttpsConfigurator. (server-ssl-context)))
    (.createContext server "/"
                    (reify HttpHandler
                      (handle [_ exchange]
                        (swap! hits conj (str (.getPath (.getRequestURI ^HttpExchange exchange))))
                        (swap! headers conj
                               (into {} (map (fn [[k v]] [(str/lower-case (str k)) (vec v)]))
                                     (.getRequestHeaders ^HttpExchange exchange)))
                        (handler exchange))))
    (.start server)
    (try
      (body {:hits hits :headers headers
             :origin (str "https://127.0.0.1:" (.getPort (.getAddress server)))})
      (finally (.stop server 0)))))

(defn- respond! [^HttpExchange exchange status ^bytes bytes]
  (.sendResponseHeaders exchange status (alength bytes))
  (with-open [out (.getResponseBody exchange)] (.write out bytes))
  (.close exchange))

(defn- serve-hello [^HttpExchange exchange]
  (respond! exchange 200 (.getBytes ^String hello "UTF-8")))

(defn- policy-for
  "The storage policy for ORIGIN on TRANSPORT, pinning the server's own key to
  the host it is reached as."
  ([origin transport] (policy-for origin transport {"127.0.0.1" {:pins #{(server-pin)}}}))
  ([origin transport anchors]
   {:aiueos.policy/net-allow #{"127.0.0.1"}
    :aiueos.cloud/transport transport
    :aiueos.cloud/storage-origin origin
    :aiueos.cloud/trust-anchors anchors}))

;; ── the own path does what the platform path does ─────────────────────────

(deftest a-block-arrives-over-tls-this-workspace-implemented
  (with-https-server serve-hello
    (fn [s]
      (let [v (provider/read-block! (policy-for (:origin s) :own) raw-cid)]
        (is (cloud/allowed? v))
        (is (= hello-digest (:aiueos.cloud/digest v))
            "the bytes hash to what the CID commits to, and org-ietf-tls carried them")
        (is (= (server-pin) (:aiueos.provider.cloud/peer-spki v))
            "the receipt names the key it talked to")
        (is (= :host (:aiueos.provider.cloud/peer-anchor-binding v))
            "and that it was accepted FOR this host, not merely found in the policy")
        (is (= "127.0.0.1" (:aiueos.provider.cloud/peer-host v)))
        (is (= [cid-path] @(:hits s)))))))

(deftest both-transports-answer-the-same-question-the-same-way
  ;; The point of the whole change. Two stacks that disagree about which peer
  ;; is acceptable, or about what arrived, would be two policies -- and only
  ;; one of them would be the one anybody read.
  (with-https-server serve-hello
    (fn [s]
      (let [jdk (provider/read-block! (policy-for (:origin s) :jdk) raw-cid)
            own (provider/read-block! (policy-for (:origin s) :own) raw-cid)]
        (is (cloud/allowed? jdk))
        (is (cloud/allowed? own))
        (is (= (:aiueos.cloud/digest jdk) (:aiueos.cloud/digest own) hello-digest))
        (is (= (:aiueos.provider.cloud/peer-spki jdk) (:aiueos.provider.cloud/peer-spki own))
            "one pin, measured two ways from the same DER, agreeing to the hex digit --
             `tls.cert/spki-sha256-hex` over the parsed SubjectPublicKeyInfo and
             `PublicKey.getEncoded` over the platform's re-encoding of it")
        (is (= (:aiueos.provider.cloud/status jdk) (:aiueos.provider.cloud/status own) 200))
        (is (= (:aiueos.provider.cloud/byte-count jdk)
               (:aiueos.provider.cloud/byte-count own)
               (count hello)))))))

;; ── the peer verdict is `grant.cloud/admit-peer`'s on both paths ──────────

(deftest a-peer-outside-the-pin-set-is-refused-mid-handshake
  (doseq [transport [:jdk :own]]
    (testing (str "transport " transport)
      (with-https-server serve-hello
        (fn [s]
          (let [wrong (apply str (repeat 64 "a"))
                v (provider/read-block!
                   (policy-for (:origin s) transport {"127.0.0.1" {:pins #{wrong}}})
                   raw-cid)]
            (is (= :peer-not-pinned (:aiueos.provider.cloud/error v))
                "reported as the refusal it was, not as the transport error it became")
            (is (= (server-pin) (:aiueos.cloud/observed-spki v))
                "and it says which key it saw -- without that, rotation and attack
                 look identical")
            (is (= [] @(:hits s))
                "the request was never made: the handshake did not complete")))))))

(deftest the-same-key-pinned-to-another-host-is-refused-mid-handshake
  (doseq [transport [:jdk :own]]
    (testing (str "transport " transport)
      (with-https-server serve-hello
        (fn [s]
          (let [v (provider/read-block!
                   (policy-for (:origin s) transport
                               {"127.0.0.1" {:pins #{(apply str (repeat 64 "a"))}}
                                "kotobase.net" {:pins #{(server-pin)}}})
                   raw-cid)]
            (is (= :peer-pinned-to-other-host (:aiueos.provider.cloud/error v))
                "the very key this server holds, pinned to somebody else")
            (is (= ["kotobase.net"] (:aiueos.cloud/pinned-for v)))
            (is (= [] @(:hits s)))))))))

(deftest https-without-anchors-never-reaches-the-socket-on-either-transport
  (doseq [transport [:jdk :own]]
    (testing (str "transport " transport)
      (with-https-server serve-hello
        (fn [s]
          (let [v (provider/read-block! (policy-for (:origin s) transport {}) raw-cid)]
            (is (= :no-trust-anchors (:aiueos.provider.cloud/error v)))
            (is (= [] @(:hits s)))))))))

(deftest the-tls-library-is-never-asked-to-judge-the-pin
  ;; `tls.client` can authenticate against a pin itself. It is not asked to:
  ;; `verify-chain` is handed the whole decision, and it forwards it to
  ;; `grant.cloud/admit-peer`. Two pin checks that could disagree is worse than
  ;; one, so this asserts the seam directly rather than through a socket -- a
  ;; policy that admits nothing must refuse, and the SAME leaf under a policy
  ;; that admits it must pass, with no pin ever handed to `tls.client`.
  (let [leaf-der (.getEncoded ^X509Certificate (.getCertificate ^KeyStore @keystore "aiueos"))
        raw (jvm/provider)
        parsed (cert/parse-certificate-message
                (byte-array (concat [0]
                                    ;; certificate_list length, 3 octets
                                    (let [n (+ 3 (alength leaf-der) 2)]
                                      [(bit-and (bit-shift-right n 16) 0xff)
                                       (bit-and (bit-shift-right n 8) 0xff)
                                       (bit-and n 0xff)])
                                    (let [n (alength leaf-der)]
                                      [(bit-and (bit-shift-right n 16) 0xff)
                                       (bit-and (bit-shift-right n 8) 0xff)
                                       (bit-and n 0xff)])
                                    (map #(bit-and % 0xff) leaf-der)
                                    [0 0])))]
    (is (= :ok (first parsed)) (str "certificate fixture did not parse: " (pr-str parsed)))
    (let [leaf (:tls/leaf (second parsed))
          entries (:tls/entries (second parsed))
          run (fn [anchors]
                (let [verdict (atom nil)
                      f (own/verify-chain raw {:aiueos.cloud/trust-anchors anchors}
                                          "127.0.0.1" verdict)]
                  [(f leaf entries) @verdict]))
          [allowed v-allowed] (run {"127.0.0.1" {:pins #{(server-pin)}}})
          [refused v-refused] (run {"127.0.0.1" {:pins #{(apply str (repeat 64 "a"))}}})]
      (is (= :ok (first allowed)))
      (is (= :grant.cloud/admit-peer (:tls/authenticated-by (second allowed)))
          "the value names who decided, so a reader cannot mistake it for a pin
           the TLS library checked")
      (is (= (server-pin) (:tls/spki-sha256 (second allowed))))
      (is (cloud/allowed? v-allowed))
      (is (= :error (first refused)))
      (is (= :peer-not-pinned (:tls/reason (second refused))))
      (is (= :peer-not-pinned (:aiueos.cloud/reason v-refused))
          "and the refusal is recorded even though the handshake will report an alert")
      (is (contains? (:tls/not-checked (second allowed)) :chain-to-trust-anchor)
          "what an ok does NOT mean is in the value, not only in the docstring"))))

;; ── the four behaviours the docstring calls load-bearing ──────────────────

(defn- serve-redirect [^HttpExchange exchange]
  (if (= "/elsewhere" (.getPath (.getRequestURI exchange)))
    (respond! exchange 200 (.getBytes "somewhere else" "UTF-8"))
    (do (.add (.getResponseHeaders exchange) "Location" "/elsewhere")
        (respond! exchange 302 (byte-array 0)))))

(deftest a-redirect-is-a-status-and-never-a-second-request
  ;; The allowlist checked the URL *we* chose, not the one the server names
  ;; next. A followed 302 would leave the allowlist behind while still looking
  ;; like a successful fetch.
  (doseq [transport [:jdk :own]]
    (testing (str "transport " transport)
      (with-https-server serve-redirect
        (fn [s]
          (let [v (provider/read-block! (policy-for (:origin s) transport) raw-cid)]
            (is (not (cloud/allowed? v)))
            (is (= 302 (:aiueos.provider.cloud/status v))
                "the redirect is reported as the status it is")
            (is (= [cid-path] @(:hits s))
                "and /elsewhere was never requested")))))))

(defn- serve-n-bytes [n]
  (fn [^HttpExchange exchange]
    (respond! exchange 200 (byte-array n (byte 97)))))

(deftest the-body-ceiling-refuses-rather-than-truncates
  ;; Both directions on both transports: at the ceiling the body arrives and is
  ;; measured, one octet over it the request produces no digest at all. A
  ;; truncated body hashes to something, and that something would be reported
  ;; as a measurement.
  (doseq [transport [:jdk :own]]
    (testing (str "transport " transport)
      (with-https-server (serve-n-bytes 64)
        (fn [s]
          (let [at (provider/read-block! (policy-for (:origin s) transport) raw-cid
                                         {:max-bytes 64})]
            (is (= 64 (:aiueos.provider.cloud/byte-count at))
                "at the ceiling the body arrives whole"))))
      (with-https-server (serve-n-bytes 65)
        (fn [s]
          (let [over (provider/read-block! (policy-for (:origin s) transport) raw-cid
                                           {:max-bytes 64})]
            (is (= :response-too-large (:aiueos.provider.cloud/error over)))
            (is (nil? (:aiueos.cloud/digest over))
                "no digest: a truncated body would have produced one")
            (is (nil? (:aiueos.provider.cloud/status over))
                "and no status, because nothing this machine will act on arrived")))))))

(deftest a-request-that-could-not-complete-yields-no-status-and-no-digest
  (doseq [transport [:jdk :own]]
    (testing (str "transport " transport)
      ;; A port nothing is listening on: bind one, read the number, close it.
      (let [port (with-open [probe (ServerSocket. 0)] (.getLocalPort probe))
            v (provider/read-block!
               (policy-for (str "https://127.0.0.1:" port) transport) raw-cid
               {:connect-timeout-ms 2000 :request-timeout-ms 2000})]
        (is (= :request-failed (:aiueos.provider.cloud/error v)))
        (is (nil? (:aiueos.provider.cloud/status v)))
        (is (nil? (:aiueos.cloud/digest v)))
        (is (not (cloud/allowed? v)))))))

(deftest a-socket-that-never-answers-becomes-a-value-not-an-escaping-exception
  ;; The one place a throw can still come from on the own path is the socket,
  ;; and `SocketTimeoutException` arrives from inside the handshake rather than
  ;; through the wire layer's transport seam. Both paths must return.
  (doseq [transport [:jdk :own]]
    (testing (str "transport " transport)
      (let [listener (ServerSocket. 0 1 (java.net.InetAddress/getByName "127.0.0.1"))
            port (.getLocalPort listener)
            accepted (atom [])
            thread (doto (Thread. #(try (swap! accepted conj (.accept listener))
                                        (Thread/sleep 30000)
                                        (catch Exception _ nil)))
                     (.setDaemon true) (.start))]
        (try
          (let [v (provider/read-block!
                   (policy-for (str "https://127.0.0.1:" port) transport) raw-cid
                   {:connect-timeout-ms 2000 :request-timeout-ms 1500})]
            (is (= :request-failed (:aiueos.provider.cloud/error v))
                "a peer that accepts and says nothing is unreachable, not refused")
            (is (nil? (:aiueos.provider.cloud/status v))))
          (finally
            (.interrupt thread)
            (doseq [^java.net.Socket sock @accepted] (.close sock))
            (.close listener)))))))

(defn- echo-json [^HttpExchange exchange]
  (respond! exchange 200 (.getBytes "{\"ok\":true}" "UTF-8")))

(deftest a-credential-reaches-the-request-and-nothing-else
  ;; Two halves, and the first is what makes the second mean anything: the
  ;; header MUST have reached the server, or "the token is not in the verdict"
  ;; is true of a request that never carried one.
  (doseq [transport [:jdk :own]]
    (testing (str "transport " transport)
      (with-https-server echo-json
        (fn [s]
          (let [secret "s3cret-token-do-not-log"
                policy (assoc (policy-for (:origin s) transport)
                              :aiueos.cloud/inference-origin (:origin s)
                              :aiueos.cloud/liveness-path "/ready")
                v (provider/ready! policy {:headers {"authorization" (str "Bearer " secret)}})]
            (is (= 1 (count @(:hits s))) "sanity: exactly one request was made")
            (is (= [(str "Bearer " secret)]
                   (get (first @(:headers s)) "authorization"))
                "the credential reached the request -- without this the rest is vacuous")
            (doseq [[label text] [["the verdict" (pr-str v)]
                                  ["the receipt leg" (pr-str (live/verdict-leg :inference-liveness v {} :admitted))]
                                  ["the receipt line" (live/leg-line (live/verdict-leg :inference-liveness v {} :admitted))]]]
              (is (not (str/includes? text secret))
                  (str "the credential must not travel with the thing that was measured: " label)))))))))

(deftest a-json-body-goes-out-and-the-response-is-judged
  ;; The POST shape the inference leg needs. The `GET` path is the proven one;
  ;; this is the one the murakumo leg actually uses.
  (let [body (atom nil)]
    (with-https-server (fn [^HttpExchange exchange]
                         (reset! body (vec (.readAllBytes (.getRequestBody exchange))))
                         (echo-json exchange))
      (fn [s]
        (let [policy (assoc (policy-for (:origin s) :own)
                            :aiueos.cloud/inference-origin (:origin s))
              model {:endpoint (str (:origin s) "/v1/chat/completions") :alias "murakumo-main"}
              v (provider/infer! policy model {:messages [{:role "user" :content "ping"}]
                                               :max-tokens 8} {})
              seen (first @(:headers s))
              sent (String. (byte-array (map unchecked-byte @body)) "UTF-8")]
          (is (= ["application/json"] (get seen "content-type"))
              "the body was framed as JSON without the caller saying so")
          (is (= [(str (count @body))] (get seen "content-length"))
              "and Content-Length is the body's own length, measured against the
               octets that actually arrived rather than against a constant")
          (is (str/includes? sent "\"max_tokens\":8")
              "the plan's body reached the server as JSON")
          (is (= 200 (:aiueos.provider.cloud/status v)))
          ;; The authority answered a shape `grant.cloud` does not accept as a
          ;; completion, so the verdict is a refusal -- which is the right answer
          ;; and proves the response was actually judged rather than assumed.
          (is (not (cloud/allowed? v)))
          (is (some? (:aiueos.cloud/reason v))))))))

(deftest bytes-a-caller-supplies-go-out-verbatim
  ;; `write-block!`'s rule: a block write must not be reshaped by a serialiser.
  (let [payload (.getBytes ^String hello "UTF-8")
        seen (atom nil)]
    (with-https-server (fn [^HttpExchange exchange]
                         (reset! seen (vec (.readAllBytes (.getRequestBody exchange))))
                         (respond! exchange 201 (byte-array 0)))
      (fn [s]
        (let [v (provider/write-block! (policy-for (:origin s) :own) raw-cid payload {})]
          (is (= (vec payload) @seen)
              "the octets on the wire are the caller's own, byte for byte")
          (is (some? (:aiueos.provider.cloud/status v))))))))

;; ── the transport is chosen, never guessed ────────────────────────────────

(deftest the-default-transport-is-the-platform-one
  (is (= :jdk (provider/transport-of {})))
  (is (= :jdk provider/default-transport))
  (is (= :own (provider/transport-of {:aiueos.cloud/transport :own}))))

(deftest an-unknown-transport-is-a-fault-not-a-fallback
  (with-https-server serve-hello
    (fn [s]
      (let [v (provider/read-block!
               (assoc (policy-for (:origin s) :own) :aiueos.cloud/transport :onw)
               raw-cid)]
        (is (= :transport-unknown (:aiueos.provider.cloud/error v))
            "a machine told to use a stack it does not have must not quietly use
             the other one")
        (is (= [] @(:hits s)))))))

(deftest the-own-transport-refuses-a-plaintext-url
  ;; `grant.cloud` refuses plaintext at plan time as `:insecure-transport`, so
  ;; the only way to reach this branch is the operator escape hatch that the
  ;; loopback suites use. That is exactly the deployment where the difference
  ;; matters: a policy carrying both `:allow-insecure-origins` and
  ;; `:transport :own` must not silently get the platform stack.
  (let [plain {:aiueos.policy/net-allow #{"127.0.0.1"}
               :aiueos.cloud/storage-origin "http://127.0.0.1:1"
               :aiueos.cloud/trust-anchors {"127.0.0.1" {:pins #{(server-pin)}}}}
        insecure (assoc plain :aiueos.cloud/allow-insecure-origins #{"http://127.0.0.1:1"})]
    (is (= :insecure-transport
           (:aiueos.cloud/reason (provider/read-block! (assoc plain :aiueos.cloud/transport :own) raw-cid)))
        "sanity: without the escape hatch this never reaches a transport at all")
    (is (= :transport-scheme-unsupported
           (:aiueos.provider.cloud/error
            (provider/read-block! (assoc insecure :aiueos.cloud/transport :own) raw-cid)))
        "this path speaks https and nothing else, and says so rather than
         handing the request to the transport it was told not to use")
    (is (= :request-failed
           (:aiueos.provider.cloud/error
            (provider/read-block! (assoc insecure :aiueos.cloud/transport :jdk) raw-cid
                                  {:connect-timeout-ms 1000 :request-timeout-ms 1000})))
        "and the platform path does try, which is what makes the refusal above a
         difference between the two rather than a property of the URL")))

(deftest the-live-gate-flag-refuses-a-word-it-does-not-know
  (is (= [:ok nil] (live/transport-arg ["check"])))
  (is (= [:ok :own] (live/transport-arg ["check" "--transport" "own"])))
  (is (= [:ok :jdk] (live/transport-arg ["check" "--transport" "jdk"])))
  (is (= [:error "onw"] (live/transport-arg ["check" "--transport" "onw"]))
      "a typo must not be rounded to the default: the gate would then report a
       green run of the stack the operator was trying not to use"))

(deftest the-receipt-says-which-stack-the-bytes-went-through
  (is (= :own (provider/transport-of (live/with-transport {} :own))))
  (is (= :jdk (provider/transport-of (live/with-transport {} nil)))
      "no flag leaves the policy file's answer alone"))

;; ── classifying what the wire layer refuses ───────────────────────────────

(deftest wire-refusals-are-sorted-into-the-three-answers-a-gate-can-give
  (let [ceiling (own/fault-of :body-too-large {:limit 8} 8)
        incomplete (own/fault-of :truncated-body {:missing 4} 8)
        unframable (own/fault-of :conflicting-content-length {:values ["4" "5"]} 8)]
    (is (= :response-too-large (:aiueos.provider.cloud/error ceiling)))
    (is (= :request-failed (:aiueos.provider.cloud/error incomplete))
        "a body that stopped arriving could not be measured")
    (is (= :response-unframable (:aiueos.provider.cloud/error unframable))
        "a response framed two incompatible ways is a refusal that names the
         authority, not a network that was unavailable")
    ;; Through the gate's own classifier, not through the private set it reads:
    ;; what matters is the word an operator sees on the line.
    (is (= :unmeasured (live/outcome-of incomplete))
        "so the live gate reports it UNMEASURED")
    (is (= :refused (live/outcome-of unframable))
        "and reports the other REFUSED, taking the exit code with it")
    (is (= :refused (live/outcome-of ceiling)))
    (is (= 3 (live/exit-code [{:outcome (live/outcome-of incomplete)}])))
    (is (= 1 (live/exit-code [{:outcome (live/outcome-of unframable)}])))))

(deftest every-fault-this-path-can-produce-is-declared
  (is (every? #(contains? provider/errors %) own/errors)
      "a fault the provider can emit and does not declare is a fault nothing
       downstream has a case for")
  (is (contains? provider/errors :transport-unknown)))
