(ns aiueos.provider.cloud-tls-test
  "Real TLS, on loopback, against a certificate this test generates.

  What is proved here is that the machine's trust in the cloud is **the pin
  set in its policy** and nothing else: the same certificate that the JDK's
  default trust store rejects is accepted when its key is pinned, and rejected
  when it is not."
  (:require [grant.cloud :as cloud]
            [aiueos.provider.cloud :as provider]
            [clojure.java.io :as io]
            [clojure.test :refer [deftest is]])
  (:import [com.sun.net.httpserver HttpExchange HttpHandler HttpsConfigurator HttpsServer]
           [java.net InetSocketAddress URI]
           [java.net.http HttpClient HttpRequest HttpResponse$BodyHandlers]
           [java.security KeyStore]
           [java.security.cert X509Certificate]
           [javax.net.ssl KeyManagerFactory SSLContext]))

(def hello "hello world")
(def hello-digest "b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9")
(def raw-cid "bafkreifzjut3te2nhyekklss27nh3k72ysco7y32koao5eei66wof36n5e")
(def cid-path (str "/ipfs/" raw-cid))
(def store-pass "changeit")

(defn- keytool-path []
  (str (System/getProperty "java.home") "/bin/keytool"))

(def ^:private keystore
  "One self-signed certificate for 127.0.0.1, generated by the JDK's own
  keytool. Generated rather than checked in, because a private key in the
  repository is a private key in the repository."
  (delay
    (let [dir (doto (io/file (System/getProperty "java.io.tmpdir")
                             (str "aiueos-tls-" (System/currentTimeMillis)))
                (.mkdirs))
          path (str (io/file dir "server.p12"))
          {:keys [exit err]}
          (let [pb (ProcessBuilder.
                    ^"[Ljava.lang.String;"
                    (into-array String [(keytool-path) "-genkeypair" "-alias" "aiueos"
                                        "-keyalg" "RSA" "-keysize" "2048"
                                        "-sigalg" "SHA256withRSA"
                                        "-dname" "CN=localhost" "-validity" "1"
                                        "-keystore" path "-storetype" "PKCS12"
                                        "-storepass" store-pass "-keypass" store-pass
                                        "-ext" "SAN=IP:127.0.0.1"]))
                proc (.start (.redirectErrorStream pb true))
                out (slurp (.getInputStream proc))]
            {:exit (.waitFor proc) :err out})]
      ;; A missing keytool must fail the test, not skip it: a suite that
      ;; silently does not run reports the same green as one that ran.
      (assert (zero? exit) (str "keytool failed: " err))
      (let [ks (KeyStore/getInstance "PKCS12")]
        (with-open [in (io/input-stream path)]
          (.load ks in (.toCharArray store-pass)))
        ks))))

(defn- server-pin []
  (provider/spki-sha256-hex ^X509Certificate (.getCertificate ^KeyStore @keystore "aiueos")))

(defn- server-ssl-context ^SSLContext []
  (let [kmf (KeyManagerFactory/getInstance (KeyManagerFactory/getDefaultAlgorithm))]
    (.init kmf ^KeyStore @keystore (.toCharArray store-pass))
    (doto (SSLContext/getInstance "TLS")
      (.init (.getKeyManagers kmf) nil nil))))

(defn- with-https-server [handler body]
  (let [server (HttpsServer/create (InetSocketAddress. "127.0.0.1" 0) 0)
        hits (atom [])]
    (.setHttpsConfigurator server (HttpsConfigurator. (server-ssl-context)))
    (.createContext server "/"
                    (reify HttpHandler
                      (handle [_ exchange]
                        (swap! hits conj (str (.getPath (.getRequestURI ^HttpExchange exchange))))
                        (handler exchange))))
    (.start server)
    (try
      (body {:hits hits :origin (str "https://127.0.0.1:" (.getPort (.getAddress server)))})
      (finally (.stop server 0)))))

(defn- serve-hello [^HttpExchange exchange]
  (let [bytes (.getBytes ^String hello "UTF-8")]
    (.sendResponseHeaders exchange 200 (alength bytes))
    (with-open [out (.getResponseBody exchange)]
      (.write out bytes))
    (.close exchange)))

(defn- policy-for [origin pins]
  {:aiueos.policy/net-allow #{"127.0.0.1"}
   :aiueos.cloud/storage-origin origin
   :aiueos.cloud/trust-anchors pins})

;; ── the pin is the whole of the trust decision ────────────────────────────

(deftest a-pinned-peer-serves-a-block-over-real-tls
  (with-https-server serve-hello
    (fn [s]
      (let [pin (server-pin)
            v (provider/read-block! (policy-for (:origin s) #{pin}) raw-cid)]
        (is (cloud/allowed? v))
        (is (= hello-digest (:aiueos.cloud/digest v)))
        (is (= pin (:aiueos.provider.cloud/peer-spki v))
            "the receipt names the key it talked to")
        (is (= [cid-path] @(:hits s)))))))

(deftest a-peer-outside-the-pin-set-is-refused-mid-handshake
  (with-https-server serve-hello
    (fn [s]
      (let [wrong (apply str (repeat 64 "a"))
            v (provider/read-block! (policy-for (:origin s) #{wrong}) raw-cid)]
        (is (= :peer-not-pinned (:aiueos.provider.cloud/error v))
            "reported as the refusal it was, not as the I/O error it became")
        (is (= (server-pin) (:aiueos.cloud/observed-spki v))
            "and it says which key it saw")
        (is (= [] @(:hits s))
            "the request was never made: the handshake did not complete")))))

(deftest https-without-anchors-never-reaches-the-socket
  (with-https-server serve-hello
    (fn [s]
      (let [v (provider/read-block! (policy-for (:origin s) #{}) raw-cid)]
        (is (= :no-trust-anchors (:aiueos.provider.cloud/error v))
            "nothing was declared, so there was no verdict to be had")
        (is (= [] @(:hits s)))))))

;; ── the platform trust store is replaced, not extended ────────────────────

(deftest the-default-trust-store-rejects-the-certificate-that-the-pin-accepts
  (with-https-server serve-hello
    (fn [s]
      (let [url (str (:origin s) cid-path)]
        (is (thrown? Exception
                     (.send (HttpClient/newHttpClient)
                            (.build (.uri (HttpRequest/newBuilder) (URI/create url)))
                            (HttpResponse$BodyHandlers/ofString)))
            "an ordinary JDK client cannot reach this server at all")
        (is (cloud/allowed?
             (provider/read-block! (policy-for (:origin s) #{(server-pin)}) raw-cid))
            "aiueos reaches it, and the only reason is the pin")))))

;; ── the measurement itself ────────────────────────────────────────────────

(deftest the-pin-is-over-the-key-not-the-certificate
  (let [cert ^X509Certificate (.getCertificate ^KeyStore @keystore "aiueos")
        pin (provider/spki-sha256-hex cert)]
    (is (= 64 (count pin)))
    (is (re-matches #"[0-9a-f]{64}" pin))
    (is (not= pin (provider/sha256-hex (.getEncoded cert)))
        "hashing the whole certificate would change on renewal; hashing the
         SubjectPublicKeyInfo changes when the key does")))
