(ns aiueos.provider.cloud-tls-test
  "Real TLS, on loopback, against a certificate this test generates.

  What is proved here is that the machine's trust in the cloud is **the pin
  set in its policy** and nothing else: the same certificate that the JDK's
  default trust store rejects is accepted when its key is pinned, and rejected
  when it is not."
  (:require [grant.cloud :as cloud]
            [aiueos.provider.cloud :as provider]
            [clojure.java.io :as io]
            [clojure.test :refer [deftest is]])
  (:import [com.sun.net.httpserver HttpExchange HttpHandler HttpsConfigurator HttpsServer]
           [java.net InetSocketAddress URI]
           [java.net.http HttpClient HttpRequest HttpResponse$BodyHandlers]
           [java.security KeyStore]
           [java.security.cert X509Certificate]
           [javax.net.ssl KeyManagerFactory SSLContext]))

(def hello "hello world")
(def hello-digest "b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9")
(def raw-cid "bafkreifzjut3te2nhyekklss27nh3k72ysco7y32koao5eei66wof36n5e")
(def cid-path (str "/ipfs/" raw-cid))
(def store-pass "changeit")

(defn- keytool-path []
  (str (System/getProperty "java.home") "/bin/keytool"))

(def ^:private keystore
  "One self-signed certificate for 127.0.0.1, generated by the JDK's own
  keytool. Generated rather than checked in, because a private key in the
  repository is a private key in the repository."
  (delay
    (let [dir (doto (io/file (System/getProperty "java.io.tmpdir")
                             (str "aiueos-tls-" (System/currentTimeMillis)))
                (.mkdirs))
          path (str (io/file dir "server.p12"))
          {:keys [exit err]}
          (let [pb (ProcessBuilder.
                    ^"[Ljava.lang.String;"
                    (into-array String [(keytool-path) "-genkeypair" "-alias" "aiueos"
                                        "-keyalg" "RSA" "-keysize" "2048"
                                        "-sigalg" "SHA256withRSA"
                                        "-dname" "CN=localhost" "-validity" "1"
                                        "-keystore" path "-storetype" "PKCS12"
                                        "-storepass" store-pass "-keypass" store-pass
                                        "-ext" "SAN=IP:127.0.0.1"]))
                proc (.start (.redirectErrorStream pb true))
                out (slurp (.getInputStream proc))]
            {:exit (.waitFor proc) :err out})]
      ;; A missing keytool must fail the test, not skip it: a suite that
      ;; silently does not run reports the same green as one that ran.
      (assert (zero? exit) (str "keytool failed: " err))
      (let [ks (KeyStore/getInstance "PKCS12")]
        (with-open [in (io/input-stream path)]
          (.load ks in (.toCharArray store-pass)))
        ks))))

(defn- server-pin []
  (provider/spki-sha256-hex ^X509Certificate (.getCertificate ^KeyStore @keystore "aiueos")))

(defn- server-ssl-context ^SSLContext []
  (let [kmf (KeyManagerFactory/getInstance (KeyManagerFactory/getDefaultAlgorithm))]
    (.init kmf ^KeyStore @keystore (.toCharArray store-pass))
    (doto (SSLContext/getInstance "TLS")
      (.init (.getKeyManagers kmf) nil nil))))

(defn- with-https-server [handler body]
  (let [server (HttpsServer/create (InetSocketAddress. "127.0.0.1" 0) 0)
        hits (atom [])]
    (.setHttpsConfigurator server (HttpsConfigurator. (server-ssl-context)))
    (.createContext server "/"
                    (reify HttpHandler
                      (handle [_ exchange]
                        (swap! hits conj (str (.getPath (.getRequestURI ^HttpExchange exchange))))
                        (handler exchange))))
    (.start server)
    (try
      (body {:hits hits :origin (str "https://127.0.0.1:" (.getPort (.getAddress server)))})
      (finally (.stop server 0)))))

(defn- serve-hello [^HttpExchange exchange]
  (let [bytes (.getBytes ^String hello "UTF-8")]
    (.sendResponseHeaders exchange 200 (alength bytes))
    (with-open [out (.getResponseBody exchange)]
      (.write out bytes))
    (.close exchange)))

(defn- policy-for [origin pins]
  {:aiueos.policy/net-allow #{"127.0.0.1"}
   :aiueos.cloud/storage-origin origin
   :aiueos.cloud/trust-anchors pins})

;; ── the pin is the whole of the trust decision ────────────────────────────

(deftest a-pinned-peer-serves-a-block-over-real-tls
  (with-https-server serve-hello
    (fn [s]
      (let [pin (server-pin)
            v (provider/read-block! (policy-for (:origin s) #{pin}) raw-cid)]
        (is (cloud/allowed? v))
        (is (= hello-digest (:aiueos.cloud/digest v)))
        (is (= pin (:aiueos.provider.cloud/peer-spki v))
            "the receipt names the key it talked to")
        (is (= [cid-path] @(:hits s)))))))

(deftest a-peer-outside-the-pin-set-is-refused-mid-handshake
  (with-https-server serve-hello
    (fn [s]
      (let [wrong (apply str (repeat 64 "a"))
            v (provider/read-block! (policy-for (:origin s) #{wrong}) raw-cid)]
        (is (= :peer-not-pinned (:aiueos.provider.cloud/error v))
            "reported as the refusal it was, not as the I/O error it became")
        (is (= (server-pin) (:aiueos.cloud/observed-spki v))
            "and it says which key it saw")
        (is (= [] @(:hits s))
            "the request was never made: the handshake did not complete")))))

(deftest https-without-anchors-never-reaches-the-socket
  (with-https-server serve-hello
    (fn [s]
      (let [v (provider/read-block! (policy-for (:origin s) #{}) raw-cid)]
        (is (= :no-trust-anchors (:aiueos.provider.cloud/error v))
            "nothing was declared, so there was no verdict to be had")
        (is (= [] @(:hits s)))))))

;; ── the platform trust store is replaced, not extended ────────────────────

(deftest the-default-trust-store-rejects-the-certificate-that-the-pin-accepts
  (with-https-server serve-hello
    (fn [s]
      (let [url (str (:origin s) cid-path)]
        (is (thrown? Exception
                     (.send (HttpClient/newHttpClient)
                            (.build (.uri (HttpRequest/newBuilder) (URI/create url)))
                            (HttpResponse$BodyHandlers/ofString)))
            "an ordinary JDK client cannot reach this server at all")
        (is (cloud/allowed?
             (provider/read-block! (policy-for (:origin s) #{(server-pin)}) raw-cid))
            "aiueos reaches it, and the only reason is the pin")))))

;; ── the measurement itself ────────────────────────────────────────────────

(deftest the-pin-is-over-the-key-not-the-certificate
  (let [cert ^X509Certificate (.getCertificate ^KeyStore @keystore "aiueos")
        pin (provider/spki-sha256-hex cert)]
    (is (= 64 (count pin)))
    (is (re-matches #"[0-9a-f]{64}" pin))
    (is (not= pin (provider/sha256-hex (.getEncoded cert)))
        "hashing the whole certificate would change on renewal; hashing the
         SubjectPublicKeyInfo changes when the key does")))

;; ── the pin is a pin FOR A HOST ───────────────────────────────────────────
;;
;; The loopback server is reached as `127.0.0.1`, so that is the host the
;; provider must tell `grant.cloud/admit-peer` about. These are the same
;; handshake as above, differing only in which host the policy binds the key
;; to — which is exactly the distinction the flat set could not make.

(defn- host-policy-for [origin bindings]
  {:aiueos.policy/net-allow #{"127.0.0.1"}
   :aiueos.cloud/storage-origin origin
   :aiueos.cloud/trust-anchors bindings})

(deftest a-key-pinned-to-this-host-serves-a-block-over-real-tls
  (with-https-server serve-hello
    (fn [s]
      (let [pin (server-pin)
            v (provider/read-block!
               (host-policy-for (:origin s) {"127.0.0.1" {:pins #{pin}}})
               raw-cid)]
        (is (cloud/allowed? v))
        (is (= hello-digest (:aiueos.cloud/digest v)))
        (is (= pin (:aiueos.provider.cloud/peer-spki v)))
        (is (= :host (:aiueos.provider.cloud/peer-anchor-binding v))
            "and the receipt records that it was accepted FOR this host, not
             merely that the key was somewhere in the policy")
        (is (= "127.0.0.1" (:aiueos.provider.cloud/peer-host v)))
        (is (= [cid-path] @(:hits s)))))))

(deftest the-same-key-pinned-to-another-host-is-refused-mid-handshake
  (with-https-server serve-hello
    (fn [s]
      (let [pin (server-pin)
            ;; Both hosts are pinned, and each to the other's key -- the shape
            ;; the live policy has, with the two entries swapped. A policy that
            ;; simply forgot this host is `a-host-with-no-pins-...` below.
            v (provider/read-block!
               (host-policy-for (:origin s)
                                {"127.0.0.1" {:pins #{(apply str (repeat 64 "a"))}}
                                 "kotobase.net" {:pins #{pin}}})
               raw-cid)]
        (is (= :peer-pinned-to-other-host (:aiueos.provider.cloud/error v))
            "the very key this server holds, pinned to somebody else: under the
             flat set this handshake completed and served a block")
        (is (= ["kotobase.net"] (:aiueos.cloud/pinned-for v))
            "and it says whose key the policy thinks this is")
        (is (= [] @(:hits s))
            "the request was never made: the handshake did not complete")))))

(deftest a-host-with-no-pins-is-refused-before-the-key-is-judged
  (with-https-server serve-hello
    (fn [s]
      (let [v (provider/read-block!
               (host-policy-for (:origin s) {"kotobase.net" {:pins #{(apply str (repeat 64 "a"))}}})
               raw-cid)]
        (is (= :host-not-pinned (:aiueos.provider.cloud/error v))
            "an operator who has not said, in the host dimension -- which is a
             different fix from a peer that presented the wrong key")
        (is (= "127.0.0.1" (:aiueos.cloud/host v)))
        (is (= [] @(:hits s)))))))

(deftest a-flat-set-still-works-and-still-says-that-it-is-flat
  (with-https-server serve-hello
    (fn [s]
      (let [pin (server-pin)
            v (provider/read-block! (policy-for (:origin s) #{pin}) raw-cid)]
        (is (cloud/allowed? v)
            "a device booted from a release-borne anchor set has no host field
             to bind to, and refusing it would strand exactly the machines the
             anchors plane exists for")
        (is (= :unbound (:aiueos.provider.cloud/peer-anchor-binding v))
            "and every verdict from it says so"))
      (let [strict (assoc (policy-for (:origin s) #{(server-pin)})
                          :aiueos.cloud/require-host-bound-anchors? true)]
        (is (= :trust-anchors-unbound
               (:aiueos.provider.cloud/error (provider/read-block! strict raw-cid)))
            "a deployment that can bind hosts refuses a policy that does not,
             which is how the live policy cannot regress to the weaker shape")))))

;; ── a rotation window, over a real handshake ─────────────────────────────

(deftest during-an-overlap-window-the-retiring-key-still-serves
  (with-https-server serve-hello
    (fn [s]
      (let [pin (server-pin)
            rotating (fn [now]
                       (assoc (host-policy-for
                               (:origin s)
                               {"127.0.0.1" {:pins #{(apply str (repeat 64 "b"))}
                                             :previous #{pin}
                                             :accept-previous-until-ms 5000}})
                              :aiueos.cloud/now-ms now))]
        (is (cloud/allowed? (provider/read-block! (rotating 4999) raw-cid))
            "mid-rotation a Cloudflare edge serves the old key from some POPs
             and the new one from others; a client that accepts exactly one of
             them goes red on a healthy authority")
        (let [v (provider/read-block! (rotating 5001) raw-cid)]
          (is (= :peer-pin-expired (:aiueos.provider.cloud/error v))
              "and after the window the clock retires it -- named as the
               schedule it is, not as an attack")
          (is (= 5000 (:aiueos.cloud/accept-previous-until-ms v))))))))

(deftest a-refused-peer-names-the-key-it-saw-on-every-leg-not-only-the-storage-ones
  ;; `read-block!` short-circuits on a fault and returns the peer verdict whole,
  ;; so the storage legs always named the key they refused. The murakumo legs go
  ;; through `judged`, which builds a fresh verdict -- and printed `:measured {}`
  ;; beside the same refusal. One refusal an operator can act on and one they
  ;; cannot is two different checks wearing one name.
  (with-https-server serve-hello
    (fn [s]
      (let [policy {:aiueos.policy/net-allow #{"127.0.0.1"}
                    :aiueos.cloud/inference-origin (:origin s)
                    :aiueos.cloud/trust-anchors
                    {"127.0.0.1" {:pins #{(apply str (repeat 64 "a"))}}
                     "kotobase.net" {:pins #{(server-pin)}}}}
            v (provider/ready! policy)]
        (is (= :peer-pinned-to-other-host (:aiueos.provider.cloud/error v)))
        (is (= (server-pin) (:aiueos.cloud/observed-spki v))
            "the liveness leg says which key it saw")
        (is (= "127.0.0.1" (:aiueos.cloud/host v)))
        (is (= ["kotobase.net"] (:aiueos.cloud/pinned-for v))
            "and whose key the policy thinks it is")))))
